# pyproject.toml
[project]
name = "comfyui-customnodekit" # Unique identifier for your node. Immutable after creation.
description = "一套为 ComfyUI 设计的自定义节点工具集，涵盖视频生成、姿态处理、图像交互操作等常见工作流需求"
version = "1.0.6" # Custom Node version. Must be semantically versioned.
license = { text = "MIT" }
dependencies = [] # Filled in from requirements.txt

[project.urls]
Repository = "https://github.com/user2318/ComfyUI-CustomNodeKit"

[tool.comfy]
PublisherId = "user2318" # TODO (fill in Publisher ID from Comfy Registry Website).
DisplayName = "Custom Node Kit" # Display name for the Custom Node. Can be changed later.
Icon = ""